inherit_from:
  AllCops:
    NewCops: enable
    TargetRubyVersion: 3.2  # Change to your Ruby version

  Style/Documentation:
    Enabled: false

    inherit_gem: { rubocop-rails-omakase: rubocop.yml }
